### PR TITLE
W.I.P Finished installing Less

### PR DESCRIPTION
**Pull request by adfaris**
I have installed and is running LESS

### CODE REVIEW

**Comment by adfaris** [comment]
converted selector chains to nested selectors, changed block comments to line comment, added media query, introduced a color variable to change few items from the site.

**Comment by adfaris** [comment]
Corrected nested selectors

**Comment by AndjDavis** [comment]
Hey, this is looking really good.  Your code is laid out very cleanly, very easy to read.  I really like seeing that.  Makes my job easy.  Overall, everything looks good.  There one task from the project that I'm not seeing.  
    'Find a way to use at least two different operators like + or * to do something to the layout.' - if you used that and I just missed it let me know.  Shouldn't be too difficult to go back and add two of those in real quick.
  One more quick note, and I know I've said this already, but with your commit messages, keep trying to make them more detailed.  for example, instead of saying 'corrected some errors' write out what errors they were and what file they were in.  Some of your comments do have that level of detail, I just want to see them all do that.  Great job!

**Comment by adfaris** [comment]
I went through it and added addition and multiplication to complete the assignment.

**Pull request closed without merging**
